### ISSUE TITLE
500 Error when opening Sales > Orders page in Magento 2

### ISSUE THREAD

**Issue by pietervanuhm** [paynl/magento2-plugin#35]
Hi,

After update to 1.4.5 we get an 500 error on the Sales > Order page.

Error log:
`2018/11/09 06:59:57 [error] 4933#4933: *1180173 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Paynl\Payment\Model\Paymentmethod\PaymentMethod in /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
Stack trace:
#0 /data/web/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Paynl\\Payment\\M...', Array)
#1 /data/web/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Paynl\\Payment\\M...', Array)
#2 /data/web/magento2/vendor/magento/module-payment/Model/Method/Factory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Paynl\\Payment\\M...', Array)
#3 /data/web/magento2/vendor/magento/module-payment/Helper/Data.php(114): Magento\Payment\Model\Method\Factory->create('Paynl\\Payment\\M...')
#4 /data/web/magento2/vendor/magento/module-payment/Helper/Data.php(273): Magento\Payment\Helper\Data->getMethodIn" while reading response header from upstream, client: 86.86.99.95, server: , request: "GET /hairworldshop_admin/sales/invoice/index/key/c33afd29972ed69328994ffec2c920c101876e4d19c975ff1b113df0ce016ce0/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.hairworldshop.nl", referrer: "https://www.hairworldshop.nl/hairworldshop_admin/admin/cache/index/key/b34e1979a002a9569a66490e6bcb1b98c678f664c00c20530699fd06fd0043e5/"
2018/11/09 0`

For now i will downgrade back to 1.4.3.

**Comment by andypieters** [comment]
Really strange this issue didn't come up when i was testing this.
Sorry about that.
I understand the error, instead of using the paylink method, i used the PaymentMethod base class.
That class is abstract, so if magento instaniates it, it will throw this error.

**Comment by pietervanuhm** [comment]
No problem, let me know when you have a update.

**Comment by andypieters** [comment]
Strange, i an unable to trigger this error on my side.
Maybe it's the php version, i am using 7.1.23. What php version are you using?
Anyway, before i release a new version with the chance it doesn't work. can you try if the latest version works for you?

composer require paynl/magento2-plugin:dev-master

I expect it will work but yesterday it worked for me too.
If you can't test it, can you please tell me the php and magento version you are using, so i can test it with the same version.
